import{a as b,S as L,i as a}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const S="47430297-39549c12782b3a6dbb0b94f2b",q="https://pixabay.com/api/";async function w(e,o){try{return(await b.get(q,{params:{key:S,q:e,page:o,per_page:15,image_type:"photo",orientation:"horizontal"}})).data}catch(n){throw console.error("Error not found images: ",n),n}}const m=document.querySelector(".gallery");let c;function v(e){const o=e.map(({webformatURL:n,largeImageURL:i,tags:t,likes:r,views:s,comments:p,downloads:h})=>`<a href="${i}" class="gallery-item">
    <img src="${n}" alt="${t}" loading="lazy" />
    <div class="info">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${s}</p>
        <p><b>Comments:</b> ${p}</p>
        <p><b>Downloads:</b> ${h}</p>
    </div>
    </a>`).join("");m.insertAdjacentHTML("beforeend",o),c?c.refresh():c=new L(".gallery a")}function I(){m.innerHTML=" "}function E(){const e=document.querySelector(".loader");e&&e.classList.remove("hidden")}function P(){const e=document.querySelector(".loader");e&&e.classList.add("hidden")}const $=document.querySelector(".form"),O=document.querySelector(".input"),d=document.querySelector(".load-more-btn"),A=document.querySelector(".gallery");document.querySelector(".loader");let u=!0,y="",l=1,f=0;$.addEventListener("submit",H);d.addEventListener("click",M);function H(e){e.preventDefault();const o=O.value.trim();if(o===""){a.error({title:"Error",message:"Please enter a search query"});return}y=o,I(),l=1,g()}async function g(){try{E();const e=await w(y,l);if(f=e.totalHits,e.hits.length===0){a.info({title:"Info",message:"Sorry, we couldn't find the image."});return}v(e.hits),e.hits.length<15||l*15>=f?(u=!1,d.classList.add("hidden"),a.info({title:"End",message:"We're sorry, but you've reached the end of search results."})):(u=!0,d.style.display="block")}catch{a.error({title:"Error",message:"An error occurred. Try again!"})}finally{P()}}async function M(){if(!u)return;l+=1,await g();const e=A.querySelector(".gallery-item");if(e){const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
